#!/bin/bash

append_option_vars() {
  local -n _out=$1
  shift
  local env val flag
  local -a parts
  for env in "$@"; do
    local -n _src="$env"
    val="${_src:-}"
    unset -n _src
    [[ -z "$val" ]] && continue
    flag="--$(printf '%s' "$env" | tr '[:upper:]_' '[:lower:]-')"
    read -r -a parts <<< "$val"
    _out+=("$flag" "${parts[@]}")
  done
  return 0
}

# For each ENV VAR name: append the bare `--flag` iff the var == "1".
append_flag_vars() {
  local -n _out=$1
  shift
  local env flag
  for env in "$@"; do
    local -n _src="$env"
    if [[ "${_src:-}" == "1" ]]; then
      flag="--$(printf '%s' "$env" | tr '[:upper:]_' '[:lower:]-')"
      _out+=("$flag")
    fi
    unset -n _src
  done
  return 0
}

# ===========================================================================
# ARGUMENT REGISTRY  —  edit here to add/remove parameters.
# One env var name per line. Grouped after arguments.py add_*_arguments().
# ===========================================================================

# Env vars that MUST be set (argparse required=True). Empty -> abort early.
REQUIRED_ENV_VARS=(
  ROLLOUT_BATCH_SIZE
)

# ---- add_cluster_arguments ----
CLUSTER_OPTS=(
  ACTOR_NUM_NODES
  ACTOR_NUM_GPUS_PER_NODE
  CRITIC_NUM_NODES
  CRITIC_NUM_GPUS_PER_NODE
  ROLLOUT_NUM_GPUS
  ROLLOUT_NUM_GPUS_PER_ENGINE
  NUM_GPUS_PER_NODE
  OFFLOAD_ROLLOUT_LEVEL          # multi-value
  DISTRIBUTED_BACKEND
  DISTRIBUTED_TIMEOUT_MINUTES
)
CLUSTER_FLAGS=(
  COLOCATE
  OFFLOAD
  OFFLOAD_TRAIN
  NO_OFFLOAD_TRAIN
  OFFLOAD_ROLLOUT
  NO_OFFLOAD_ROLLOUT
)

# ---- add_train_arguments ----
TRAIN_OPTS=(
  TRAIN_BACKEND
  QKV_FORMAT
  TRAIN_ENV_VARS                 # JSON (use compact, no spaces)
  TRAIN_MEMORY_MARGIN_BYTES
  MEGATRON_TO_HF_MODE
  EXTRA_HIGH_PRECISION_LAYERS_HF        # multi-value
  EXTRA_HIGH_PRECISION_LAYERS_MEGATRON  # multi-value
  CUSTOM_MODEL_PROVIDER_PATH
  LOG_PROBS_CHUNK_SIZE
)
TRAIN_FLAGS=(
  TRUE_ON_POLICY_MODE
  RECOMPUTE_LOGPROBS_VIA_PREFILL
  DEBUG_SKIP_WEIGHT_UPDATE
  DEBUG_DISABLE_OPTIMIZER
  DISABLE_WEIGHTS_BACKUPER
  RECOMPUTE_LOSS_FUNCTION
  ALLGATHER_CP
  LOW_MEMORY_RESUME
)

# ---- add_rollout_arguments ----
ROLLOUT_OPTS=(
  HF_CHECKPOINT
  MODEL_NAME
  ROLLOUT_FUNCTION_PATH
  ROLLOUT_TEMPERATURE
  ROLLOUT_TOP_P
  ROLLOUT_TOP_K
  ROLLOUT_MAX_CONTEXT_LEN
  ROLLOUT_MAX_PROMPT_LEN
  ROLLOUT_MAX_RESPONSE_LEN
  ROLLOUT_STOP                   # multi-value
  ROLLOUT_STOP_TOKEN_IDS         # multi-value
  ROLLOUT_REPEAT_MIN_COUNT
  ROLLOUT_REPEAT_MIN_LENGTH
  ROLLOUT_REPEAT_MAX_LENGTH
  ROLLOUT_SEED
  OVER_SAMPLING_BATCH_SIZE
  DYNAMIC_SAMPLING_FILTER_PATH
  MAX_WEIGHT_STALENESS
  CUSTOM_GENERATE_FUNCTION_PATH
  CUSTOM_ROLLOUT_LOG_FUNCTION_PATH
  CUSTOM_EVAL_ROLLOUT_LOG_FUNCTION_PATH
  BUFFER_FILTER_PATH
  UPDATE_WEIGHT_BUFFER_SIZE
  UPDATE_WEIGHTS_INTERVAL
  PAUSE_GENERATION_MODE
  ROLLOUT_DATA_POSTPROCESS_PATH
  ROLLOUT_EXTERNAL_ENGINE_ADDRS  # multi-value
  UPDATE_WEIGHT_TRANSFER_MODE
  P2P_TRANSFER_NUM_WORKERS
  P2P_TRANSFER_TIMEOUT
)
ROLLOUT_FLAGS=(
  ROLLOUT_SKIP_SPECIAL_TOKENS
  ROLLOUT_SHUFFLE
  PARTIAL_ROLLOUT
  MASK_OFFPOLICY_IN_PARTIAL_ROLLOUT
  KEEP_OLD_ACTOR
  PIN_ROLLOUT_MANAGER_TO_HEAD
  ROLLOUT_EXTERNAL
)

# ---- add_fault_tolerance_arguments ----
FAULT_TOLERANCE_OPTS=(
  ROLLOUT_HEALTH_CHECK_INTERVAL
  ROLLOUT_HEALTH_CHECK_TIMEOUT
  ROLLOUT_HEALTH_CHECK_FIRST_WAIT
)
FAULT_TOLERANCE_FLAGS=(
  USE_FAULT_TOLERANCE
)

# ---- add_data_arguments ----
DATA_OPTS=(
  NUM_ROLLOUT
  NUM_EPOCH
  DATA_SOURCE_PATH
  PROMPT_DATA
  APPLY_CHAT_TEMPLATE_KWARGS     # JSON (use compact, no spaces)
  CHAT_TEMPLATE_PATH
  INPUT_KEY
  LABEL_KEY
  MULTIMODAL_KEYS                # JSON (use compact, no spaces)
  METADATA_KEY
  TOOL_KEY
  DATA_PREFILTER_PATH
  START_ROLLOUT_ID
  ROLLOUT_BATCH_SIZE             # required (see REQUIRED_ENV_VARS)
  N_SAMPLES_PER_PROMPT
  GLOBAL_BATCH_SIZE
  NUM_STEPS_PER_ROLLOUT
  MICRO_BATCH_SIZE
  MAX_TOKENS_PER_GPU
  LOG_PROBS_MAX_TOKENS_PER_GPU
)
DATA_FLAGS=(
  DISABLE_ROLLOUT_GLOBAL_DATASET
  APPLY_CHAT_TEMPLATE
  BALANCE_DATA
  USE_DYNAMIC_BATCH_SIZE
)

# ---- add_eval_arguments ----
EVAL_OPTS=(
  EVAL_FUNCTION_PATH
  EVAL_INTERVAL
  EVAL_PROMPT_DATA               # multi-value (name path name path ...)
  EVAL_CONFIG
  EVAL_INPUT_KEY
  EVAL_LABEL_KEY
  EVAL_TOOL_KEY
  N_SAMPLES_PER_EVAL_PROMPT
  EVAL_TEMPERATURE
  EVAL_TOP_P
  EVAL_TOP_K
  EVAL_MAX_RESPONSE_LEN
  EVAL_MAX_PROMPT_LEN
  EVAL_MIN_NEW_TOKENS
  EVAL_MAX_CONTEXT_LEN
)
EVAL_FLAGS=(
  SKIP_EVAL_BEFORE_TRAIN
)

# ---- add_algo_arguments ----
ALGO_OPTS=(
  REF_LOAD
  REF_CKPT_STEP
  PPO_EPOCHS
  LOAD
  SAVE
  SAVE_INTERVAL
  SAVE_HF
  SEED
  CLIP_GRAD
  SKIP_UPDATE_GRAD_NORM_THRESHOLD
  LR
  NUM_CRITIC_ONLY_STEPS
  CRITIC_LOAD
  CRITIC_SAVE
  CRITIC_LR
  CRITIC_LR_WARMUP_ITERS
  EPS_CLIP
  EPS_CLIP_HIGH
  EPS_CLIP_C
  DPPO_DELTA
  DPPO_DIVERGENCE
  VALUE_CLIP
  KL_COEF
  LOSS_TYPE
  CUSTOM_LOSS_FUNCTION_PATH
  KL_LOSS_TYPE
  ADVANTAGE_ESTIMATOR
  KL_LOSS_COEF
  REF_UPDATE_INTERVAL
  ENTROPY_COEF
  GAMMA
  LAMBD
  TIS_CLIP
  TIS_CLIP_LOW
  CUSTOM_TIS_FUNCTION_PATH
  CUSTOM_PG_LOSS_REDUCER_FUNCTION_PATH
  OPSM_DELTA
)
ALGO_FLAGS=(
  ASYNC_SAVE
  NO_SAVE_OPTIM
  CALCULATE_PER_TOKEN_LOSS
  DISABLE_COMPUTE_ADVANTAGES_AND_RETURNS
  USE_KL_LOSS
  USE_UNBIASED_KL
  NORMALIZE_ADVANTAGES
  DISABLE_GRPO_STD_NORMALIZATION
  DISABLE_REWARDS_NORMALIZATION
  USE_ROLLOUT_ENTROPY
  GET_MISMATCH_METRICS
  RESET_OPTIMIZER_STATES
  USE_ROLLOUT_LOGPROBS
  USE_TIS
  USE_ROUTING_REPLAY
  USE_ROLLOUT_ROUTING_REPLAY
  USE_OPSM
)

# ---- add_lora_arguments ----
LORA_OPTS=(
  LORA_RANK
  LORA_ALPHA
  LORA_DROPOUT
  LORA_TYPE
  TARGET_MODULES
  EXCLUDE_MODULES
  LORA_ADAPTER_PATH
)
LORA_FLAGS=(
  LORA_SYNC_FROM_TENSOR
)

# ---- add_router_arguments (miles-router; RouterArgs.add_cli_args is dynamic) ----
ROUTER_OPTS=(
  MILES_ROUTER_MIDDLEWARE_PATHS  # multi-value
  MILES_ROUTER_TIMEOUT
  MILES_ROUTER_MAX_CONNECTIONS
  MILES_ROUTER_HEALTH_CHECK_FAILURE_THRESHOLD
  ROUTER_RETRY_MAX_RETRIES
  ROUTER_RETRY_INITIAL_BACKOFF_MS
  ROUTER_RETRY_MAX_BACKOFF_MS
  ROUTER_RETRY_BACKOFF_MULTIPLIER
)
ROUTER_FLAGS=(
  USE_MILES_ROUTER
  ROUTER_DP_AWARE
)

# ---- add_wandb_arguments ----
# NB: WANDB_KEY -> --wandb-key, WANDB_HOST -> --wandb-host. The wandb SDK's own
# WANDB_API_KEY / WANDB_BASE_URL are passed separately via build_runtime_env_json.
WANDB_OPTS=(
  WANDB_MODE
  WANDB_DIR
  WANDB_KEY
  WANDB_HOST
  WANDB_TEAM
  WANDB_GROUP
  WANDB_PROJECT
  LOG_REWARD_CATEGORY
  WANDB_RUN_ID
)
WANDB_FLAGS=(
  USE_WANDB
  DISABLE_WANDB_RANDOM_SUFFIX
  WANDB_ALWAYS_USE_TRAIN_STEP
  LOG_MULTI_TURN
  LOG_PASSRATE
  LOG_CORRECT_SAMPLES
)

# ---- add_mlflow_arguments ----
MLFLOW_OPTS=(
  MLFLOW_TRACKING_URI
  MLFLOW_EXPERIMENT_NAME
  MLFLOW_RUN_NAME
  MLFLOW_RUN_ID
)
MLFLOW_FLAGS=(
  USE_MLFLOW
)

# ---- add_tensorboard_arguments ----
TENSORBOARD_OPTS=(
  TB_PROJECT_NAME
  TB_EXPERIMENT_NAME
)
TENSORBOARD_FLAGS=(
  USE_TENSORBOARD
)

# ---- add_prometheus_arguments ----
PROMETHEUS_OPTS=(
  PROMETHEUS_PORT
  PROMETHEUS_RUN_NAME
)
PROMETHEUS_FLAGS=(
  USE_PROMETHEUS
)

# ---- add_debug_arguments ----
DEBUG_OPTS=(
  SAVE_DEBUG_ROLLOUT_DATA
  LOAD_DEBUG_ROLLOUT_DATA
  LOAD_DEBUG_ROLLOUT_DATA_SUBSAMPLE
  SAVE_DEBUG_TRAIN_DATA
  DUMP_DETAILS
  DUMPER_DIR
  DUMPER_INFERENCE               # multi-value (key=value ...)
  DUMPER_FWD_ONLY                # multi-value (key=value ...)
  DUMPER_FWD_BWD                 # multi-value (key=value ...)
  DUMPER_SOURCE_PATCHER_CONFIG_INFERENCE
  DUMPER_SOURCE_PATCHER_CONFIG_TRAIN
  MEMORY_SNAPSHOT_DIR
  MEMORY_SNAPSHOT_NUM_STEPS
  PROFILE_TARGET                 # multi-value
  MEMORY_RECORDER
  ENV_REPORT
)
DEBUG_FLAGS=(
  DEBUG_ROLLOUT_ONLY
  DEBUG_TRAIN_ONLY
  DUMPER_ENABLE
  CHECK_WEIGHT_UPDATE_EQUAL
)

# ---- add_network_arguments ----
NETWORK_OPTS=(
  HTTP_PROXY
)
NETWORK_FLAGS=(
  # Spread HTTP POSTs across per-node Ray actors so JSON decode + response parse
  # don't all serialize on the single RolloutManager GIL.
  USE_DISTRIBUTED_POST
)

# ---- add_reward_model_arguments ----
REWARD_MODEL_OPTS=(
  RM_TYPE
  REWARD_KEY
  EVAL_REWARD_KEY
  RM_URL
  CUSTOM_RM_PATH
  CUSTOM_REWARD_POST_PROCESS_PATH
  CUSTOM_CONVERT_SAMPLES_TO_TRAIN_DATA_PATH
)
REWARD_MODEL_FLAGS=(
  GROUP_RM
)

# ---- add_rollout_buffer_arguments ----
ROLLOUT_BUFFER_OPTS=(
  ROLLOUT_BUFFER_URL
  SNR_FILTER_KEEP_RATIO
  FETCH_TRAJECTORY_RETRY_TIMES
  MIN_BATCH_COLLECTION_RATIO
  ROLLOUT_TASK_TYPE
  LOSS_MASK_TYPE
  DATA_PAD_SIZE_MULTIPLIER
  ROLLOUT_SAMPLE_FILTER_PATH
  ROLLOUT_ALL_SAMPLES_PROCESS_PATH
)
ROLLOUT_BUFFER_FLAGS=(
  DISABLE_ROLLOUT_TRIM_SAMPLES
  USE_DYNAMIC_GLOBAL_BATCH_SIZE
)

# ---- add_custom_megatron_plugins_arguments ----
CUSTOM_MEGATRON_PLUGINS_OPTS=(
  CUSTOM_MEGATRON_INIT_PATH
  CUSTOM_MEGATRON_BEFORE_LOG_PROB_HOOK_PATH
  CUSTOM_MEGATRON_BEFORE_TRAIN_STEP_HOOK_PATH
)
CUSTOM_MEGATRON_PLUGINS_FLAGS=()

# ---- add_mtp_training_arguments ----
MTP_TRAINING_OPTS=(
  MTP_NUM_LAYERS
  MTP_LOSS_SCALING_FACTOR
)
MTP_TRAINING_FLAGS=(
  ENABLE_MTP_TRAINING
  EXCLUDE_MTP_GRAD
)

# ---- add_prefill_decode_disaggregation_arguments ----
PREFILL_DECODE_OPTS=(
  PREFILL_NUM_SERVERS
)
PREFILL_DECODE_FLAGS=()

# ---- add_ci_arguments ----
CI_OPTS=(
  CI_METRIC_CHECKER_KEY
  CI_METRIC_CHECKER_THRESHOLD
  CI_SAVE_GRAD_NORM
  CI_LOAD_GRAD_NORM
)
CI_FLAGS=(
  CI_TEST
  CI_DISABLE_KL_CHECKER
  CI_DISABLE_LOGPROBS_CHECKER
  CI_SAVE_MODEL_HASH
  CI_CHECK_MODEL_HASH
)

# ---- add_session_arguments ----
SESSION_OPTS=(
  SESSION_SERVER_IP
  SESSION_SERVER_PORT
  TITO_MODEL
  TITO_ALLOWED_APPEND_ROLES      # multi-value
)
SESSION_FLAGS=(
  USE_SESSION_SERVER
)

# ---- top-level reset_arg() (custom-config-path, padded-vocab-size) ----
MISC_RESET_OPTS=(
  CUSTOM_CONFIG_PATH
  PADDED_VOCAB_SIZE
)
MISC_RESET_FLAGS=()

# ---- add_sglang_arguments: explicit args (the rest of ServerArgs is dynamic) ----
SGLANG_OPTS=(
  SGLANG_ROUTER_IP
  SGLANG_ROUTER_PORT
  SGLANG_ROUTER_POLICY
  SGLANG_ROUTER_REQUEST_TIMEOUT_SECS
  SGLANG_SERVER_CONCURRENCY
  SGLANG_CONFIG
)
SGLANG_FLAGS=()

# ---- sglang ServerArgs (auto-prefixed --sglang-*; not declared in arguments.py
#      but valid CLI flags). Commonly used set; add more by name as needed. ----
SGLANG_SERVERARGS_OPTS=(
  SGLANG_MEM_FRACTION_STATIC
  SGLANG_EP_SIZE
  SGLANG_CUDA_GRAPH_BS           # multi-value
  SGLANG_DP_SIZE
  SGLANG_MOE_DENSE_TP_SIZE
  SGLANG_EP_NUM_REDUNDANT_EXPERTS
  SGLANG_MOE_A2A_BACKEND
  SGLANG_MAX_MAMBA_CACHE_SIZE
  SGLANG_MAMBA_FULL_MEMORY_RATIO
  SGLANG_MAX_RUNNING_REQUESTS
  SGLANG_MAX_QUEUED_REQUESTS
  SGLANG_CHUNKED_PREFILL_SIZE
  SGLANG_MAMBA_SCHEDULER_STRATEGY
  SGLANG_SCHEDULE_POLICY
  SGLANG_SCHEDULE_CONSERVATIVENESS
  SGLANG_WATCHDOG_TIMEOUT
  SGLANG_PREFILL_DELAYER_TOKEN_USAGE_LOW_WATERMARK
  SGLANG_SPECULATIVE_ALGORITHM
  SGLANG_SPECULATIVE_NUM_STEPS
  SGLANG_SPECULATIVE_EAGLE_TOPK
  SGLANG_SPECULATIVE_NUM_DRAFT_TOKENS
)
SGLANG_SERVERARGS_FLAGS=(
  SGLANG_ENABLE_DP_ATTENTION
  SGLANG_ENABLE_DP_LM_HEAD
  SGLANG_ENABLE_PREFILL_DELAYER
  SGLANG_ALLOW_AUTO_TRUNCATE
)

# ---- Megatron-defined args used by run_lib (optimizer / parallelism / recompute
#      / attention / checkpoint resume). Not in arguments.py; valid CLI flags. ----
MEGATRON_OPTS=(
  OPTIMIZER
  LR_DECAY_STYLE
  WEIGHT_DECAY
  ADAM_BETA1
  ADAM_BETA2
  TENSOR_MODEL_PARALLEL_SIZE
  PIPELINE_MODEL_PARALLEL_SIZE
  CONTEXT_PARALLEL_SIZE
  EXPERT_MODEL_PARALLEL_SIZE
  EXPERT_TENSOR_PARALLEL_SIZE
  MOE_TOKEN_DISPATCHER_TYPE
  MOE_FLEX_DISPATCHER_BACKEND
  RECOMPUTE_GRANULARITY
  RECOMPUTE_METHOD
  RECOMPUTE_NUM_LAYERS
  ATTENTION_DROPOUT
  HIDDEN_DROPOUT
  ATTENTION_BACKEND
  CROSS_ENTROPY_FUSION_IMPL
  CKPT_STEP
  MOE_TOKEN_DISPATCHER_TYPE
  MOE_FLEX_DISPATCHER_BACKEND
)
MEGATRON_FLAGS=(
  SEQUENCE_PARALLEL
  ACCUMULATE_ALLREDUCE_GRADS_IN_FP32
  ATTENTION_SOFTMAX_IN_FP32
  CROSS_ENTROPY_LOSS_FUSION
  MOE_ENABLE_DEEPEP
  NO_LOAD_OPTIM
  NO_LOAD_RNG
  FINETUNE
)

# ---- User custom passthrough (appended LAST so it overrides the registry). ----
# Add your own ENV VAR names here. Same derivation rule (FOO_BAR -> --foo-bar).
declare -p CUSTOM_OPTS &>/dev/null || CUSTOM_OPTS=()
declare -p CUSTOM_FLAGS &>/dev/null || CUSTOM_FLAGS=()

# All option/flag groups, concatenated in registry order. Add new group arrays
# to these two lists once and they flow through automatically.
ALL_OPTION_GROUPS=(
  CLUSTER_OPTS TRAIN_OPTS ROLLOUT_OPTS FAULT_TOLERANCE_OPTS DATA_OPTS EVAL_OPTS
  ALGO_OPTS LORA_OPTS ROUTER_OPTS WANDB_OPTS MLFLOW_OPTS TENSORBOARD_OPTS
  PROMETHEUS_OPTS DEBUG_OPTS NETWORK_OPTS REWARD_MODEL_OPTS ROLLOUT_BUFFER_OPTS
  CUSTOM_MEGATRON_PLUGINS_OPTS MTP_TRAINING_OPTS PREFILL_DECODE_OPTS CI_OPTS
  SESSION_OPTS MISC_RESET_OPTS SGLANG_OPTS SGLANG_SERVERARGS_OPTS MEGATRON_OPTS CUSTOM_OPTS
)
ALL_FLAG_GROUPS=(
  CLUSTER_FLAGS TRAIN_FLAGS ROLLOUT_FLAGS FAULT_TOLERANCE_FLAGS DATA_FLAGS
  EVAL_FLAGS ALGO_FLAGS LORA_FLAGS ROUTER_FLAGS WANDB_FLAGS MLFLOW_FLAGS
  TENSORBOARD_FLAGS PROMETHEUS_FLAGS DEBUG_FLAGS NETWORK_FLAGS REWARD_MODEL_FLAGS
  ROLLOUT_BUFFER_FLAGS CUSTOM_MEGATRON_PLUGINS_FLAGS MTP_TRAINING_FLAGS
  PREFILL_DECODE_FLAGS CI_FLAGS SESSION_FLAGS MISC_RESET_FLAGS SGLANG_FLAGS
  SGLANG_SERVERARGS_FLAGS MEGATRON_FLAGS CUSTOM_FLAGS
)

# Abort early (before touching the cluster) if any required env var is empty.
validate_required_env() {
  local var
  local missing=()
  for var in "${REQUIRED_ENV_VARS[@]}"; do
    [[ -z "${!var:-}" ]] && missing+=("${var}")
  done
  if ((${#missing[@]} > 0)); then
    echo "Missing required env vars (no argparse default): ${missing[*]}" >&2
    return 1
  fi
  return 0
}

# Flatten a list of group-array NAMES into one flat list of env var names.
_collect_group_names() {
  local -n _dest=$1
  shift
  local group
  for group in "$@"; do
    local -n _g="$group"
    _dest+=("${_g[@]}")
    unset -n _g
  done
  return 0
}

# Build CLI_ARGS from every registry group, then append the user passthrough last.
build_cli_args() {
  CLI_ARGS=()
  local opt_names=() flag_names=()
  _collect_group_names opt_names  "${ALL_OPTION_GROUPS[@]}"
  _collect_group_names flag_names "${ALL_FLAG_GROUPS[@]}"

  [[ ${#opt_names[@]}  -gt 0 ]] && append_option_vars CLI_ARGS "${opt_names[@]}"
  [[ ${#flag_names[@]} -gt 0 ]] && append_flag_vars   CLI_ARGS "${flag_names[@]}"
  return 0
}
